import os
import smtplib
import feedparser
from google import genai
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.header import Header

# 1. 初始化 AI 客户端
client = genai.Client(api_key=os.environ.get('GEMINI_API_KEY'))

def get_tech_news():
    """获取科技早报 HTML 格式"""
    feed = feedparser.parse("https://36kr.com/feed")
    html = "<h2 style='color: #2c3e50; border-bottom: 2px solid #3498db;'>🚀 今日科技热点</h2><ul>"
    for entry in feed.entries[:5]:
        html += f"<li style='margin-bottom: 10px;'><a href='{entry.link}' style='text-decoration:none; color:#34495e;'><b>{entry.title}</b></a></li>"
    html += "</ul><br>"
    return html

def get_cet6_article():
    """利用 AI 生成 CET-6 水平的英语阅读全文"""
    # 抓取一个英文素材（例如 ScienceDaily 的 AI 新闻）作为改写原材料
    eng_feed = feedparser.parse("https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml")
    raw_material = eng_feed.entries[0].summary if eng_feed.entries else "The evolution of sustainable energy in 2026."

    # 专门针对 CET-6 的 AI 提示词
    prompt = f"""
    Based on the following material, write a formal English passage.
    Material: {raw_material}
    
    Requirements:
    1. Level: Strictly CET-6 (College English Test Band 6) difficulty. 
    2. Grammar: Incorporate advanced structures like subjunctive mood, inverted sentences, and complex clauses.
    3. Length: Around 250 words.
    4. Format: 
       - Part 1: A Title.
       - Part 2: The full English passage.
       - Part 3: A 'Vocabulary & Expressions' list (5-8 difficult CET-6 words used in the text with English definitions).
    5. Output: Strictly English only. No Chinese.
    """
    
    response = client.models.generate_content(model="gemini-2.0-flash", contents=prompt)
    ai_text = response.text.replace('\n', '<br>')
    
    html = f"""
    <h2 style='color: #e67e22; border-bottom: 2px solid #e67e22;'>📖 CET-6 Daily Reading</h2>
    <div style='line-height: 1.8; color: #2c3e50; background: #fdfdfd; padding: 20px; border: 1px solid #eee; border-radius: 8px; font-family: "Times New Roman", Times, serif;'>
        {ai_text}
    </div>
    """
    return html

def send_email(tech_body, eng_body):
    sender = os.environ.get('GMAIL_USER')
    password = os.environ.get('GMAIL_PASS')
    
    msg = MIMEMultipart()
    msg['Subject'] = Header(f"【{os.environ.get('GITHUB_RUN_NUMBER')}期】每日科技与 CET6 专刊", 'utf-8')
    msg['From'] = sender
    msg['To'] = sender

    full_html = f"""
    <html>
        <body style='max-width: 600px; margin: auto; padding: 20px;'>
            {tech_body}
            <div style='margin-top: 30px;'>{eng_body}</div>
            <p style='text-align: center; color: #95a5a6; font-size: 12px; margin-top: 40px;'>
                Generated by GitHub Actions & Gemini AI<br>
                Keep studying, Huang.
            </p>
        </body>
    </html>
    """
    msg.attach(MIMEText(full_html, 'html', 'utf-8'))

    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
        server.login(sender, password)
        server.send_message(msg)

if __name__ == "__main__":
    try:
        t_html = get_tech_news()
        e_html = get_cet6_article()
        send_email(t_html, e_html)
        print("Done!")
    except Exception as e:
        print(f"Error occurred: {e}")
