name: Daily Report Service

on:
  schedule:
    - cron: '0 0 * * *' # 每天北京时间早上8点运行
  workflow_dispatch: # 支持手动触发测试

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run sender script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }} # 对应智谱的密钥
        run: python main.py
